name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the API Docker image
      run: docker build ./api --tag api:$(date +%s)

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ACTIONS_MAKE_PACKAGES }}

    - uses: docker/build-push-action@v5
      with:
        context: ./api
        push: true
        tags: ghcr.io/${{ github.actor }}/cc-cloud-api:latest


    - uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ghcr.io/${{ github.actor }}/cc-cloud-frontend:latest

